<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Quick_Sim_Button</name>
   <tag></tag>
   <elementGuidId>c0c7dc76-1b9b-4a8b-aaf0-1212598a811f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/section/section/div/div[2]/div/div/div[5]/div/a/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Flex</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	.st0{fill:none;stroke:#000000;stroke-width:6;stroke-miterlimit:10;}
	.st1{fill:none;stroke:#000000;stroke-width:2;stroke-miterlimit:10;}
Quick SimRun a quick sim to get your DPS and detailed stats</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;Container&quot;]/section[@class=&quot;Section&quot;]/section[@class=&quot;Section&quot;]/div[@class=&quot;Box&quot;]/div[@class=&quot;Flex&quot;]/div[@class=&quot;Box&quot;]/div[@class=&quot;Flex&quot;]/div[@class=&quot;Box&quot;]/div[@class=&quot;Box&quot;]/a[@class=&quot;LinkBlock&quot;]/div[@class=&quot;Box&quot;]/div[@class=&quot;Flex&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/section/section/div/div[2]/div/div/div[5]/div/a/div/div</value>
   </webElementXpaths>
</WebElementEntity>
