<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_generate_stat_weights</name>
   <tag></tag>
   <elementGuidId>c608a2d0-c810-4590-aa27-d34f88ec9072</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button > div.Flex > div.Box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/section/section/div[2]/section/div[7]/div/div/button/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Box</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate Stat Weights</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;Container&quot;]/section[@class=&quot;Section&quot;]/section[@class=&quot;Section&quot;]/div[2]/section[@class=&quot;Section&quot;]/div[@class=&quot;Box&quot;]/div[@class=&quot;Flex&quot;]/div[@class=&quot;Box&quot;]/button[@class=&quot;Button&quot;]/div[@class=&quot;Flex&quot;]/div[@class=&quot;Box&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/section/section/div[2]/section/div[7]/div/div/button/div/div</value>
   </webElementXpaths>
</WebElementEntity>
